# ================= RSS 下载配置 =================

# 注意：rss_feeds 下面的 Key (例如 "Six Minute English") 必须与每日英语听力网页左侧的栏目名完全一致
# 格式: 栏目名: RSS链接
rss_feeds:
  Six Minute English: "https://podcasts.files.bbci.co.uk/p02pc9tn.rss"
  Classic Stories: "https://podcasts.files.bbci.co.uk/p02pc9s1.rss"
  Bedtime History: "https://feeds.megaphone.fm/TNM4740080425"
  CNN 10: "https://feeds.megaphone.fm/WMHY2232473209"
  Apple News Today: "https://apple.news/podcast/apple_news_today"
  GLOBAL NEWS PODCAST: "https://podcasts.files.bbci.co.uk/p02nq0gn.rss"
  The Global Story: "https://podcasts.files.bbci.co.uk/w13xtvsd.rss"
  KidNuz: "https://feeds.megaphone.fm/STM6212107967"

# 起始年份 (只下载这一年及之后的)
year_from: 2025

# 下载最新的几个 (-1 代表下载所有，正整数代表只下载最新的 N 个)
latest_num: 4

# 下载文件保存的主目录
download_folder: "rss_download"
